#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
console_title_template = "{{ .Shell }} in {{ .Folder }}"
final_space = true
version = 2.0

[[blocks]]
  alignment = "left"
  type = "prompt"

  [[blocks.segments]]
    background = "#A78CFA"
    foreground = "#193549"
    leading_diamond = "\ue0b6"
    style = "diamond"
    template = " {{ .Icon }} "
    trailing_diamond = "\ue0b0"
    type = "os"

  [[blocks.segments]]
    background = "#FF6AB3"
    foreground = "#193549"
    powerline_symbol = "\ue0b0"
    style = "powerline"
    template = " \uea83  {{ .Path }} "
    type = "path"
    [blocks.segments.properties]
      folder_separator_icon = " \ue0b1 "
      home_icon = "~"
      style = "folder"

  [[blocks.segments]]
    background = "#E4BF7F"
    background_templates = ["{{ if or (.Working.Changed) (.Staging.Changed) }}#FF9248{{ end }}", "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ff4500{{ end }}", "{{ if gt .Ahead 0 }}#B388FF{{ end }}", "{{ if gt .Behind 0 }}#B388FF{{ end }}"]
    foreground = "#193549"
    powerline_symbol = "\ue0b0"
    style = "powerline"
    template = " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} \uf692 {{ .StashCount }}{{ end }} "
    type = "git"
    [blocks.segments.properties]
      branch_max_length = 25.0
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    background = "#6495EE"
    foreground = "#193549"
    style = "plain"
    template = "<transparent>\ue0b0</> \ueba2 {{ .FormattedMs }}\u2800"
    type = "executiontime"
    [blocks.segments.properties]
      always_enabled = true

  [[blocks.segments]]
    background = "#000000"
    background_templates = ["{{ if gt .Hours 100 }}#dc3545{{ end }}", "{{ if and (lt .Hours 100) (gt .Hours 50) }}#ffc107{{ end }}", "{{ if lt .Hours 50 }}#28a745{{ end }}"]
    foreground = "#ffffff"
    foreground_templates = ["{{ if gt .Hours 100 }}#FFFFFF{{ end }}", "{{ if and (lt .Hours 100) (gt .Hours 50) }}#343a40{{ end }}", "{{ if lt .Hours 50 }}#FFFFFF{{ end }}"]
    style = "powerline"
    template = " {{.Name}} {{.Ago}} {{.Icon}} "
    type = "strava"
    [blocks.segments.properties]
      access_token = "0ccbd2ac1e37a5b84101468df3d367177fe02ab3"
      http_timeout = 1500.0
      refresh_token = "111111111111111111111111111111"

  [[blocks.segments]]
    background = "#98C379"
    background_templates = ["{{ if gt .Code 0 }}#e91e63{{ end }}"]
    foreground = "#ffffff"
    style = "diamond"
    template = "<parentBackground>\ue0b0</> \ue23a "
    trailing_diamond = "\ue0b4"
    type = "exit"
    [blocks.segments.properties]
      always_enabled = true

